task:
  clone_script: |
    git config core.autocrlf
    ECHO %CIRRUS_PR%
    ECHO %CIRRUS_BRANCH%
    IF DEFINED CIRRUS_PR (
      ECHO PR
    ) ELSE (
      ECHO MASTER
    )
  name: Cirrus CI
  choco_cache:
    folder: C:\ProgramData\chocolatey
  maven_cache:
    folder: ~/.m2
  env:
    PATH: %PATH%;C:\ProgramData\chocolatey\bin;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin;C:\Program Files\OpenJDK\openjdk-11.0.8_10\bin
  matrix:
    - windows_container:
        image: cirrusci/windowsservercore:2019
      install_script:
        - cup -y chocolatey
        - cinst -y ant
        - cinst -y maven
        - cinst -y openjdk11
        - cinst -y xsltproc
        - cinst -y xmlstarlet
#    - container:
#        image: ubuntu:bionic
#        use_in_memory_disk: true
#      install_script:
#        - export RUNLEVEL=1
#        - apt-get update
#        - apt-get install -y ant maven openjdk-11-jdk xsltproc xmlstarlet
  version_script:
    - SET PATH=%PATH%;C:\ProgramData\chocolatey\bin;C:\Program Files\OpenJDK\openjdk-11.0.8_10\bin;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin
    - ant -version
    - java --version
    - mvn --version
    - xsltproc --version
    - xml --version
  test_script:
    - SET PATH=%PATH%;C:\ProgramData\chocolatey\bin;C:\Program Files\OpenJDK\openjdk-11.0.8_10\bin;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin
    - mvn clean verify
