task:
  clone_script: |
    git config core.autocrlf
    if [ -z "$CIRRUS_PR" ]; then
      git clone --recursive --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    else
      git clone --recursive https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
      git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    fi
  name: Cirrus CI
  choco_cache:
    folder: C:\ProgramData\chocolatey
  maven_cache:
    folder: ~/.m2
  env:
    PATH: %PATH%;C:\ProgramData\chocolatey\bin;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin;C:\Program Files\OpenJDK\openjdk-11.0.8_10\bin
  matrix:
    - windows_container:
        image: cirrusci/windowsservercore:2019
      install_script:
        - cup -y chocolatey
        - cinst -y ant
        - cinst -y maven
        - cinst -y openjdk11
        - cinst -y xsltproc
        - cinst -y xmlstarlet
#    - container:
#        image: ubuntu:bionic
#        use_in_memory_disk: true
#      install_script:
#        - export RUNLEVEL=1
#        - apt-get update
#        - apt-get install -y ant maven openjdk-11-jdk xsltproc xmlstarlet
  version_script:
    - SET PATH=%PATH%;C:\ProgramData\chocolatey\bin;C:\Program Files\OpenJDK\openjdk-11.0.8_10\bin;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin
    - ant -version
    - java --version
    - mvn --version
    - xsltproc --version
    - xml --version
  test_script:
    - SET PATH=%PATH%;C:\ProgramData\chocolatey\bin;C:\Program Files\OpenJDK\openjdk-11.0.8_10\bin;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin
    - mvn clean verify
