task:
  name: Windows build
  windows_container:
    image: cirrusci/windowsservercore:2019
  clone_script: >-
    git config core.autocrlf
    && IF DEFINED CIRRUS_PR (
    git clone --recursive --branch=%CIRRUS_BRANCH%
    https://x-access-token:%CIRRUS_REPO_CLONE_TOKEN%@github.com/%CIRRUS_REPO_FULL_NAME%.git
    %CIRRUS_WORKING_DIR%/ci
    ) ELSE (
    git clone --recursive
    https://x-access-token:%CIRRUS_REPO_CLONE_TOKEN%@github.com/%CIRRUS_REPO_FULL_NAME%.git
    %CIRRUS_WORKING_DIR%/ci
    && git fetch origin pull/%CIRRUS_PR%/head:pull/%CIRRUS_PR%
    )
    && git reset --hard %CIRRUS_CHANGE_IN_REPO%
  choco_cache:
    # should be under %CIRRUS_WORKING_DIR%
    folder: ".chocolatey"
  maven_cache:
    # should be under %CIRRUS_WORKING_DIR%
    folder: ".m2"
  matrix:
    env:
      OPENJDK_VERSION: "11.0.2.01"
      PATH: "%PATH%;C:/Program Files/OpenJDK/jdk-11.0.2/bin"
    env:
      OPENJDK_VERSION: "14.0.2"
      PATH: "%PATH%;C:/Program Files/OpenJDK/jdk-14.0.2/bin"
    env:
      OPENJDK_VERSION: "15.0.0"
      PATH: "%PATH%;C:/Program Files/OpenJDK/jdk-15/bin"
  env:
    # disable ANSI output for picocli (may affect tests)
    NO_COLOR: "1"
    # https://developercommunity.visualstudio.com/content/problem/357696/maven-project-build-failing-with-connection-reset.html
    MAVEN_OPTS: >-
      -Dhttp.keepAlive=false
      -Dmaven.repo.local=%CIRRUS_WORKING_DIR%/.m2
      -Dmaven.wagon.http.retryHandler.count=3
      -Dmaven.wagon.http.pool=false
    MAVEN_VERSION: "3.6.3"
    PATH: "%PATH%;\
      C:/ProgramData/chocolatey/lib/maven/apache-maven-%MAVEN_VERSION%/bin;\
      C:/ProgramData/chocolatey/bin"
  install_script: |
    choco config set cacheLocation %CIRRUS_WORKING_DIR%/.chocolatey
    cup -y chocolatey
    cinst -y ant
    cinst -y maven --version %MAVEN_VERSION%
    cinst -y openjdk --version %OPENJDK_VERSION%
    cinst -y xsltproc
    cinst -y xmlstarlet
    SET
  version_script: |
    ant -version
    java --version
    mvn --version
    xsltproc --version
    xml --version
  test_script: |
    cd ci
    mvn -e verify
    cd ..
