name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Cache .m2
      id: cache-maven-repository
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ github.head_ref }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 15.0.0-ea.17
    - name: Build with Maven
      shell: bash
      run: rm -f _config.yml; mvn -e verify
    - name: tmp
      shell: bash
      run: printenv; du -hs ${HOME}/.m2
  osx:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Cache .m2
      id: cache-maven-repository
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ github.head_ref }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 15.0.0-ea.17
    - name: Build with Maven
      shell: bash
      run: rm -f _config.yml; mvn -e verify
    - name: tmp
      shell: bash
      run: du -hs ${HOME}/.m2
  windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Cache .m2
      id: cache-maven-repository
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ github.head_ref }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 15.0.0-ea.17
    - name: Build with Maven
      shell: bash
      run: rm -f _config.yml; mvn -e verify
    - name: tmp
      shell: bash
      run: du -hs ${HOME}/.m2
